version: '2.1'

networks:
  inception:
    name: irc
    driver: bridge

services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=39738
      - PGID=4305
      - TZ=Europe/Paris
        #    networks:
        #      - irc
    volumes:
      - /mnt/nfs/homes/antton-t/Desktop/Irc_project/Wireshark:/config
    ports:
            - 4822:3000 #optional
    restart: unless-stopped

  nginx:
   image: nginx
   #  depends_on:
   #   - wireshark
   container_name: nginx
   volumes:
      - /mnt/nfs/homes/antton-t/Desktop/Irc_project/Wireshark:/config
        #   networks: 
        #      - irc
        #   ports:
        #     - 3000:3000
   restart: unless-stopped


docker run -d \
  --name=wireshark \
  --net=host \
  --cap-add=NET_ADMIN \
  -e PUID=39738 \
  -e PGID=4305 \
  -e TZ=Europe/Paris \
  -p 36000:3000 `#optional` \
  -v /mnt/nfs/homes/antton-t/Desktop/Irc_project/Wireshark:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/wireshark:latest
